version: '2'
services:
    angular4-app:
        image: angular4
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://angular4-postgresql:5432/angular4
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angular4-postgresql:
        extends:
            file: postgresql.yml
            service: angular4-postgresql
